# Generated by Django 3.0.2 on 2020-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, choices=[('GCASC_MG', 'Government College of Arts, Science and Commerce, Khandola, Marcela Goa'), ('GCASC_SG', 'Government College of Arts, Science & Commerce, Sanquelim-Goa'), ('GCASC_QG', 'Government College of Arts, Science & Commerce, Quepem-Goa'), ('SSAGCAC', 'Sant Sohirobanath Ambiye Government College of Arts & Commerce, VIrnoda-Pernem, Goa'), ('GCCE', 'Government College of Commerce & Economics, Borda-Margao, Goa'), ('GCM', 'Goa College of Music, Kala Academys Complex, Campal, Panaji-Goa'), ('GCHS', 'Goa College of Home Science, Campal, Panaji, Goa'), ('SMCAC', 'Shree Mallikarjun College of Arts & Commerce, Canacona Goa'), ('NIE', 'Nirmala Institute of Education, Altinho Panaji, Goa'), ('DCAS', 'Dhempe College of Arts & Science, Panaji, Goa'), ('VMSCL', 'V.M. Salgaocar College of law, Miramar, Panaji Goa'), ('SSDCCE', 'S.S. Dempo College of Commerce & Economics, Altinho, Panaji, Goa'), ('CCE', 'College of Commerce and Economics, Ponda Goa'), ('CCASCW', 'Carmel College of Arts, Science & Commerce for Women, Nuvem Goa'), ('RCCA', 'Rosary College of Commerce & Art, Navelim Salcete Goa'), ('FACAC', 'Fr. Agnel College of Arts & Commerce, Pilar Goa'), ('NZCC', 'Narayan Zantye College of Commerce, Bicholim Goa'), ('SPCCFCAS', "Smt. Parvatibi Chowgule Cultural Foundation's College of Arts & Science, Margao Goa"), ('CE', 'College of Education, Ponda Goa'), ('CASSPVCSVNSBCC', 'College of Arts, Sou. Sheela Premandand Vaidya College of Science & V.N.S. Bandekar College of Commerce, Assagao, Mapusa Goa'), ('SXCASC', "St. Xavier's College of Arts, Science & Commerce, Mapusa Goa"), ('SVCCMS', 'S.V. College of Commerce & Management Studies, Telang Nagar, Khorlim, Mapusa Goa'), ('MESCAC', 'MES College of Arts & Commerce, Zuarinagar Goa'), ('VVMSDCCE', "Vidya Vikas Mandal's Shree Damodar College of Commerce & Economics, Margao Goa"), ('VVMGRKCL', "Vidya Vikas Mandal's Govind Ramnath Kare College of Law Margao, Goa."), ('CESCAC', "Cuncolim Educational Society's College of Arts & Commerce, Cuncolim Salcete Goa"), ('PESCAS', "PES's College of Arts & Science, Ponda Goa")], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_college',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_rejected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passing_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
