# Generated by Django 3.0.2 on 2020-01-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200118_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Processing', 'Processing')], default='Processing', max_length=10),
        ),
    ]
