# Generated by Django 3.0.2 on 2020-01-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200118_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_college',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Alumni', 'Alumni'), ('Directorate', 'Directorate'), ('College', 'College')], default='Alumni', max_length=15),
        ),
    ]
