# Generated by Django 3.0.2 on 2020-01-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notices',
            new_name='Notice',
        ),
    ]
